source 'https://rubygems.org'
ruby '2.0.0'
gem 'sinatra'
gem "haml"
gem 'thin'
gem "less"
gem "coffee-script"
gem "thin"
gem 'therubyracer'
gem "ruby-aaws", "~> 0.7.0"
gem "nokogiri"
gem "foreman", "~> 0.63.0"
